// Generated by Wrangler by running `wrangler types`

interface Env {
  FPX_ENDPOINT: string;
  POKEMON_API_BASE: string;
  POKEDEX: DurableObjectNamespace<import("./src/Pokedex").Pokedex>;
  POKEMON_SERVICE: Fetcher<import("./src/PokemonService").PokemonService>;
}
